### ISSUE TITLE
ICMP (Ping) possible?

### ISSUE THREAD

**Issue by CorneliousJD** [shukriadams/arewedown#10]
As this is meant as an open source Uptime Robot, one of the features I use there very often is just simple ping tests to know if network devices are online or offline, is this possible to add into AreWeDown? If so I'll likely end up using it and ripping out UptimeRobot from my flow.

thanks!

**Comment by shukriadams** [comment]
Yeah, that should be doable - adding to backlog!

**Comment by shukriadams** [comment]
Done - https://github.com/shukriadams/arewedown/commit/336009cda73de88fbf57335a9c5e4baead5e2da4. Should be out in next release.

**Comment by shukriadams** [comment]
Released  in 0.2.3.
