### ISSUE TITLE
custom root path

### ISSUE THREAD

**Issue by lfoppiano** [shukriadams/arewedown#16]
I'm trying to deploy this service under a custom root path e.g. `/status` on a service. I set up a reverse proxy with Apache HTTPD but I cannot map properly http://mysevice/status because the internal URLs are pointing to `/`. 
Maybe I overlooked and there is a way to specify the custom root path? If not would be a nice addition.

**Comment by shukriadams** [comment]
AWD comes with its own HTTP server (Express) that expects to be a top-level application, so I don't think mapping to a subfolder will work. Have you tried setting Apache to proxy to localhost:3000 and then remap incoming DNS entries in Apache? I normally use Nginx to do this, but I assume they work the same.

**Comment by lfoppiano** [comment]
I see, thank you. My case is a bit different. Maybe not so usual. I want to deploy this on a server on which I don't have any control over the DNS. Maybe there is a way but did not manage to get it to work.
